name: publish github package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
                node-version: "16.x"
                registry-url: "https://npm.pkg.github.com"
                scope: "@Kris030"
          
          - run: npm install
          - run: npm publish
            env:
                NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
